spring:
  application:
    name: boardPrac
  datasource:
    url: jdbc:mariadb://localhost:3306/BOARD_PRAC
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
      # create: ?????? ?? ? ???? ?? ???? ?? ?????. (drop & create)
      # create-drop: ?????? ?? ? ???? ?? ???? ?? ?????. ??? ?????? ?? ??? ???? ?? ?????. (drop & create & drop)
      # update: ?????? ?? ? ???? ?????.
      # validate: ?? ??? ??? entity? ??? ??? ???? ?????. ?? ?? ??? ???? ??????? ????? ????.
      # none: ????? ???? ????.
  sql:
    init:
      mode: never
#  ?? ????? ??? ? ??.
#  config:
#    activate:
#      on-profile: dev
